language: c
compiler:
  - clang
  - gcc

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs

after_failure:
  - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"latest build has failed!"}' https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_CHANNEL_ID/$DISCORD_WEBHOOK_TOKEN

script:
  - npm install
  - cmake -DLIBRG_TEST=1 -DHAS_SOCKLEN_T=1
  - make
  - ./librg_test
