language: c
# compiler:
#     - clang
#     - gcc

before_install:
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - sudo apt-get install -y nodejs

after_failure:
    - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"latest build has failed!"}' https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_CHANNEL_ID/$DISCORD_WEBHOOK_TOKEN

script:
    - npm install
    - mkdir -p build
    - export FLAGS="-I include -I node_modules/zpl.c/include -I node_modules/zpl_math.c/include -I node_modules/zpl_cull.c/include -I node_modules/zpl_event.c/include -I node_modules/enet.c/include -DHAS_SOCKLEN_T=1 -pthread -lm -ldl"
    - clang   -g -std=c99 $FLAGS  test/build-test.c -o build/test-clang-c.o
    - clang++ -g -std=c++11 $FLAGS test/build-test.cpp -o build/test-clang-cpp.o
    - gcc -g -std=c99 $FLAGS test/build-test.c -o build/test-gcc-c.o
    - g++ -g -std=c++11 $FLAGS test/build-test.cpp -o build/test-gpp-cpp.o
    - build/test-clang-c.o
    - build/test-clang-cpp.o
    - build/test-gcc-c.o
    - build/test-gcc-cpp.o
