image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

before_build:
  - npm install
  - cmake . -G "Visual Studio 15 2017 Win64" -DLIBRG_TEST=1 -DLIBRG_SHARED=1

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\librg_test.exe'
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\librg_test_cpp.exe'

deploy:
  release: librg-v$(appveyor_build_version)
  description: 'librg dll compiled for windows'
  provider: GitHub
  auth_token:
    secure: tYm5oXMHHaO3oR5xd93zvnG95eqNZWw065Z9Qo6CAN3+2G7IlWbcmbsYlsl2XDFc
  artifact: /.*\.dll/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
